### ISSUE TITLE
Map tiles

### ISSUE THREAD

**Issue by LuisHsu** [AndrewZZJ/Food-chain-frontend#2]
elements from back-end:
- [x] id: the file name of the tile image.
- [x] position: the position of the tile image, containing 4 sub-elements. (refer the API)
- [x] direction: 4 different directions of an image.

elements from upper component:
- [x] width: the width of the tile image.
- [x] height: the height of the tile image.

things can be generated:
- [x] src: the url of the tile image.

**Comment by jordenchang55** [comment]
Image url of tile and card will look like `/img/<category>/<id>.svg`
For example, image of **waitress** will be `/img/employee/01.svg`
