### ISSUE TITLE
Modal - Choose reserve card

### ISSUE THREAD

**Issue by LuisHsu** [AndrewZZJ/Food-chain-frontend#7]

**Comment by AndrewZZJ** [comment]
This module simulates the choose reserve card function:
Pressing the Initialization button, meaning the module is activated by the other component.
The initial value of chosen card is 200, and the new chosen value will be stored in a variable called chosenCard.
Showing the value of chosenCard under the initialization button. If the module needs to return the value of the chosen card, use the variable mentioned above.
